name: free-games-webapp
base: core18
version: '1.1'
summary: Simple Go-Webserver 
description: This sample app shows how to create a webserver app in ctrlX CORE
grade: stable
confinement: strict

apps:
  my-server:
    command: ./bin/webserver 
    plugs:
      - network
      - network-bind
      - network-status
    daemon: simple
    restart-condition: always
    passthrough:
      restart-delay: 10s 

parts:
  simple-webserver:
    source: .
    go-importpath: github.com/mauringo/free-games-webapp
    plugin: go
    build-packages:
      - gcc
    
      
  my-server:
    plugin: dump
    source: ./static
    organize:
      '*' : static/
    

