name: free-games-webapp
version: '0.9.8'
base: core18
summary: Play on any web-based device
description: |
     Install the app and navigate to http://yourDeviceIp:23445 and Play!
      
confinement: strict
grade: stable

    
apps:

 
  flask-server: 
    command: sh $SNAP/bin/runserver.sh  
    plugs:
      - network-control
      - network-observe
      - network
      - network-bind
      - process-control
      - gsettings
      - udisks2
      - hardware-observe
      - system-observe
      - mount-observe
    daemon: simple 
    
  desktop-launch:
    command: bin/desktop-launch
    plugs:
      - desktop  
      

  info: 
    command: sh $SNAP/bin/info.sh  
    plugs: [network, network-bind, mount-observe, network-observe, system-observe, bluetooth-control]

parts:

  flask:
    plugin: python
    python-version: python3
    python-packages: [flask]
    build-packages:
      - python3-dev
      - build-essential
      


  python-code:  
    source: ./Flask/
    plugin: dump
    organize:
      '*': bin/Flask/

  shscripts:  
    source: ./shscripts/
    plugin: dump
    organize:
      '*': bin/


